version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
    reviewers:
      - "tu-usuario-github"  # cámbialo por tu nombre de usuario de GitHub

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github_actions"
